### ISSUE TITLE
Post 생성, 조회 시 카테고리 필드 설정 추가

### ISSUE THREAD

**Issue by minjo-on** [kgu-developers/aics-server#105]
### Describe

게시글 카테고리 분리를 위해 필드 설정을 추가합니다.

### Tasks

- [ ] 게시글 생성, 조회 시 query parameter로 category값 등록

### ETC

기존 구현한 기능에 추가하여 수정합니다

**Comment by LeeHanEum** [comment]
확인했습니다. 진행해주세요 👍
